import "../styles/tailwind.css";
import "../../node_modules/ol/ol.css";

import { Inter } from "next/font/google";
import { MyQueryClientProvider } from "../components/utils/view/MyQueryClientProvider";
import type { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <MyQueryClientProvider>{children}</MyQueryClientProvider>
        </body>
      </html>
    </>
  );
}
